import { useEffect, useState } from 'react'
import { auth, db } from '../lib/firebase'
import { doc, getDoc, updateDoc } from 'firebase/firestore'
import { useNavigate, useParams } from 'react-router-dom'
import { callAI } from '../lib/ai'

interface Milestone {
  id: number
  title: string
  description: string
  duration: string
  topics: string[]
  resources: string[]
  completed?: boolean
  isGap?: boolean
  needsReview?: boolean
  reviewDate?: string
  quizScore?: number
}

const topicAccents = ['#fb923c', '#f87171', '#fbbf24', '#f472b6', '#c084fc', '#facc15', '#fb923c', '#fca5a5']

export default function Roadmap() {
  const [milestones, setMilestones] = useState<Milestone[]>([])
  const [topic, setTopic] = useState('')
  const [goal, setGoal] = useState('')
  const [topicIndex, setTopicIndex] = useState(0)
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<number>(0)
  const [studyMaterial, setStudyMaterial] = useState<{ [key: number]: string }>({})
  const [tips, setTips] = useState<{ [key: number]: string[] }>({})
  const [loadingMaterial, setLoadingMaterial] = useState<number | null>(null)
  const [deepDiveWord, setDeepDiveWord] = useState('')
  const [deepDiveResult, setDeepDiveResult] = useState('')
  const [deepDiveLoading, setDeepDiveLoading] = useState(false)
  const [showDeepDive, setShowDeepDive] = useState(false)
  const navigate = useNavigate()
  const { topicId } = useParams()

  const accent = topicAccents[topicIndex % topicAccents.length]

  useEffect(() => {
    const fetchData = async () => {
      const userId = auth.currentUser?.uid
      if (!userId) { navigate('/'); return }
      const snap = await getDoc(doc(db, 'users', userId, 'roadmaps', topicId!))
      if (snap.exists()) {
        setMilestones(snap.data().milestones)
        setTopic(snap.data().topic)
        setGoal(snap.data().goal)
        setTopicIndex(parseInt(topicId!.slice(-1)) || 0)
      }
      setLoading(false)
    }
    fetchData()
  }, [topicId])

  const generateStudyMaterial = async (m: Milestone) => {
    setLoadingMaterial(m.id)
    try {
      const result = await callAI(
        `Create study material for "${m.title}" while learning ${topic}. Return a JSON object with two fields: "material" (a plain string with study notes - key concepts, explanation, and a practical exercise) and "tips" (array of 5 short actionable tip strings).`,
        'You are an expert tutor. Return valid JSON only, no markdown. The material field must be a plain string.'
      )
      const parsed = JSON.parse(result)
      const materialText = typeof parsed.material === 'string' ? parsed.material : JSON.stringify(parsed.material)
      setStudyMaterial(prev => ({ ...prev, [m.id]: materialText }))
      setTips(prev => ({ ...prev, [m.id]: parsed.tips }))
    } catch (err: any) { alert(err.message) }
    setLoadingMaterial(null)
  }

  const handleDeepDive = async () => {
    const selection = window.getSelection()?.toString().trim()
    if (!selection || selection.length < 2) return alert('Please select a word or phrase to deep dive!')
    setDeepDiveWord(selection)
    setShowDeepDive(true)
    setDeepDiveLoading(true)
    setDeepDiveResult('')
    const result = await callAI(
      `Explain "${selection}" in the context of ${topic} in simple terms. Keep it under 100 words. Be clear and direct.`,
      'You are an expert tutor. Give a concise, clear explanation.'
    )
    setDeepDiveResult(result)
    setDeepDiveLoading(false)
  }

  const downloadPDF = (m: Milestone) => {
    const content = studyMaterial[m.id]
    if (!content) return
    const html = `<html><head><title>${m.title} - Study Material</title>
    <style>body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 40px;color:#1a1a1a;line-height:1.8}h1{color:#ea580c;border-bottom:2px solid #ea580c;padding-bottom:12px}p{margin:12px 0}.footer{margin-top:48px;padding-top:16px;border-top:1px solid #ddd;color:#999;font-size:12px}</style>
    </head><body><h1>${m.title}</h1><p style="color:#666;font-size:14px">Topic: ${topic} · Duration: ${m.duration} · Generated by PromptPath</p>
    ${content.split('\n').map(line => line.trim() ? `<p>${line}</p>` : '').join('')}
    <div class="footer">Generated by PromptPath — AI-powered personalized learning</div></body></html>`
    const win = window.open('', '_blank')
    if (win) { win.document.write(html); win.document.close(); win.print() }
  }

  const getYouTubeLink = (r: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(topic + ' ' + r)}`
  const getGoogleLink = (r: string) => `https://www.google.com/search?q=${encodeURIComponent(topic + ' ' + r + ' tutorial')}`
  const getYouTubeEmbed = (r: string) => `https://www.youtube.com/embed?listType=search&list=${encodeURIComponent(topic + ' ' + r)}`

  const completed = milestones.filter(m => m.completed).length
  const activeMilestone = milestones[selected]

  if (loading) return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0a0a0a', color: 'white', fontFamily: 'sans-serif' }}>
      <div style={{ textAlign: 'center' }}><div style={{ fontSize: '40px' }}>🔥</div><p>Loading your roadmap...</p></div>
    </div>
  )

  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0a', fontFamily: 'sans-serif', color: 'white' }}>

      {/* Deep Dive Modal */}
      {showDeepDive && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '20px' }}>
          <div style={{ background: '#1a1a1a', border: '1px solid rgba(251,146,60,0.3)', borderRadius: '20px', padding: '28px', maxWidth: '500px', width: '100%' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div>
                <p style={{ fontSize: '11px', color: '#fb923c', fontWeight: 700, margin: '0 0 4px', textTransform: 'uppercase' }}>🔍 Deep Dive</p>
                <h3 style={{ margin: 0, fontSize: '20px', fontWeight: 800 }}>"{deepDiveWord}"</h3>
              </div>
              <button onClick={() => setShowDeepDive(false)} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '20px' }}>✕</button>
            </div>
            {deepDiveLoading ? (
              <p style={{ color: 'rgba(255,255,255,0.5)', fontSize: '14px' }}>Generating explanation...</p>
            ) : (
              <p style={{ color: 'rgba(255,255,255,0.85)', fontSize: '15px', lineHeight: 1.7, margin: 0 }}>{deepDiveResult}</p>
            )}
          </div>
        </div>
      )}

      {/* Navbar */}
      <div style={{ padding: '14px 24px', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#111' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <button onClick={() => navigate('/topics')} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '13px', padding: 0 }}>← Topics</button>
          <div style={{ width: '1px', height: '20px', background: 'rgba(255,255,255,0.1)' }} />
          <div>
            <h2 style={{ margin: 0, fontSize: '16px', fontWeight: 700, color: accent }}>🗺️ {topic}</h2>
            <p style={{ margin: 0, fontSize: '11px', color: 'rgba(255,255,255,0.35)' }}>Goal: {goal}</p>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.4)' }}>{completed}/{milestones.length}</span>
            <div style={{ width: '100px', height: '5px', borderRadius: '3px', background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
              <div style={{ width: `${milestones.length ? (completed / milestones.length) * 100 : 0}%`, height: '100%', background: accent, borderRadius: '3px', transition: 'width 0.5s' }} />
            </div>
          </div>
          <button onClick={() => navigate('/dashboard')} style={{ padding: '7px 14px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.05)', color: 'white', cursor: 'pointer', fontSize: '12px' }}>📊 Dashboard</button>
        </div>
      </div>

      <div style={{ display: 'flex', height: 'calc(100vh - 57px)' }}>

        {/* Sidebar */}
        <div style={{ width: '260px', flexShrink: 0, borderRight: '1px solid rgba(255,255,255,0.07)', overflowY: 'auto', padding: '16px 12px', background: '#0d0d0d' }}>
          <p style={{ fontSize: '10px', fontWeight: 700, color: 'rgba(255,255,255,0.25)', textTransform: 'uppercase', letterSpacing: '1.5px', margin: '0 0 12px 8px' }}>Milestones</p>
          {milestones.map((m, i) => (
            <div key={m.id} onClick={() => setSelected(i)}
              style={{ padding: '10px 12px', borderRadius: '10px', marginBottom: '4px', cursor: 'pointer', background: selected === i ? accent + '20' : 'transparent', border: `1px solid ${selected === i ? accent + '44' : 'transparent'}`, transition: 'all 0.15s' }}
              onMouseEnter={e => { if (selected !== i) e.currentTarget.style.background = 'rgba(255,255,255,0.04)' }}
              onMouseLeave={e => { if (selected !== i) e.currentTarget.style.background = 'transparent' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ width: '26px', height: '26px', borderRadius: '50%', flexShrink: 0, background: m.completed ? '#16a34a' : m.needsReview ? 'rgba(248,113,113,0.2)' : selected === i ? accent + '33' : 'rgba(255,255,255,0.08)', border: `1.5px solid ${m.completed ? '#16a34a' : m.needsReview ? '#f87171' : selected === i ? accent : 'rgba(255,255,255,0.1)'}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, color: m.completed ? 'white' : m.needsReview ? '#f87171' : selected === i ? accent : 'rgba(255,255,255,0.5)' }}>
                  {m.completed ? '✓' : m.needsReview ? '!' : i + 1}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ margin: 0, fontSize: '12px', fontWeight: selected === i ? 600 : 400, color: m.completed ? 'rgba(255,255,255,0.3)' : m.isGap ? '#fbbf24' : selected === i ? 'white' : 'rgba(255,255,255,0.7)', textDecoration: m.completed ? 'line-through' : 'none', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{m.title}</p>
                  <p style={{ margin: '2px 0 0', fontSize: '10px', color: m.needsReview ? '#f87171' : 'rgba(255,255,255,0.25)' }}>{m.needsReview ? '⚠️ Needs review' : m.duration}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Content */}
        {activeMilestone && (
          <div style={{ flex: 1, overflowY: 'auto', padding: '28px 36px' }}>
            <div style={{ maxWidth: '700px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '11px', fontWeight: 700, color: accent, background: accent + '20', padding: '3px 10px', borderRadius: '20px' }}>Step {selected + 1} of {milestones.length}</span>
                {activeMilestone.completed && <span style={{ fontSize: '11px', fontWeight: 700, color: '#4ade80', background: 'rgba(74,222,128,0.12)', padding: '3px 10px', borderRadius: '20px' }}>✓ Completed</span>}
                {activeMilestone.isGap && <span style={{ fontSize: '11px', fontWeight: 700, color: '#fbbf24', background: 'rgba(251,191,36,0.12)', padding: '3px 10px', borderRadius: '20px' }}>⚠️ Knowledge Gap</span>}
                {activeMilestone.needsReview && <span style={{ fontSize: '11px', fontWeight: 700, color: '#f87171', background: 'rgba(248,113,113,0.12)', padding: '3px 10px', borderRadius: '20px' }}>📅 Needs Review</span>}
                {activeMilestone.quizScore !== undefined && <span style={{ fontSize: '11px', fontWeight: 700, color: 'rgba(255,255,255,0.4)', background: 'rgba(255,255,255,0.06)', padding: '3px 10px', borderRadius: '20px' }}>Quiz: {activeMilestone.quizScore}/{5}</span>}
              </div>

              <h1 style={{ margin: '0 0 6px', fontSize: '26px', fontWeight: 800 }}>{activeMilestone.title}</h1>
              <p style={{ margin: '0 0 20px', color: 'rgba(255,255,255,0.35)', fontSize: '13px' }}>⏱ {activeMilestone.duration}</p>
              <p style={{ color: 'rgba(255,255,255,0.7)', lineHeight: 1.75, fontSize: '15px', marginBottom: '28px' }}>{activeMilestone.description}</p>

              {/* Topics */}
              <div style={{ marginBottom: '24px' }}>
                <p style={{ fontSize: '12px', color: accent, fontWeight: 700, margin: '0 0 10px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>📚 Topics covered</p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                  {activeMilestone.topics?.map(t => (
                    <span key={t} style={{ padding: '5px 14px', borderRadius: '20px', background: accent + '15', border: `1px solid ${accent}33`, fontSize: '13px', color: 'rgba(255,255,255,0.8)' }}>{t}</span>
                  ))}
                </div>
              </div>

              {/* Resources with YouTube embed */}
              <div style={{ marginBottom: '28px' }}>
                <p style={{ fontSize: '12px', color: accent, fontWeight: 700, margin: '0 0 10px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>🔗 Resources</p>
                {activeMilestone.resources?.map(r => (
                  <div key={r} style={{ marginBottom: '12px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px', padding: '10px 14px', background: 'rgba(255,255,255,0.03)', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.07)' }}>
                      <span style={{ fontSize: '13px', color: 'rgba(255,255,255,0.65)', flex: 1 }}>{r}</span>
                      <a href={getYouTubeLink(r)} target="_blank" rel="noreferrer" style={{ padding: '4px 12px', borderRadius: '7px', background: 'rgba(239,68,68,0.15)', color: '#fca5a5', fontSize: '12px', textDecoration: 'none', fontWeight: 600 }}>▶ YouTube</a>
                      <a href={getGoogleLink(r)} target="_blank" rel="noreferrer" style={{ padding: '4px 12px', borderRadius: '7px', background: 'rgba(251,146,60,0.15)', color: '#fdba74', fontSize: '12px', textDecoration: 'none', fontWeight: 600 }}>🔍 Google</a>
                    </div>
                    {/* YouTube embed */}
                    <iframe
                      src={getYouTubeEmbed(r)}
                      style={{ width: '100%', height: '200px', borderRadius: '10px', border: 'none' }}
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                      allowFullScreen
                    />
                  </div>
                ))}
              </div>

              {/* Study Material */}
              {studyMaterial[activeMilestone.id] && (
                <div style={{ marginBottom: '20px' }}>
                  <div style={{ background: 'rgba(255,255,255,0.03)', borderRadius: '14px', padding: '20px', border: `1px solid ${accent}22`, marginBottom: '16px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                      <p style={{ fontSize: '12px', color: accent, fontWeight: 700, margin: 0, textTransform: 'uppercase', letterSpacing: '0.5px' }}>✨ Study Material</p>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <button onClick={handleDeepDive} style={{ padding: '5px 12px', borderRadius: '7px', border: `1px solid ${accent}44`, background: accent + '10', color: accent, cursor: 'pointer', fontSize: '11px', fontWeight: 600 }}>🔍 Deep Dive (select text)</button>
                        <button onClick={() => downloadPDF(activeMilestone)} style={{ padding: '5px 12px', borderRadius: '7px', border: `1px solid ${accent}44`, background: accent + '10', color: accent, cursor: 'pointer', fontSize: '11px', fontWeight: 600 }}>📄 PDF</button>
                      </div>
                    </div>
                    <p style={{ fontSize: '14px', color: 'rgba(255,255,255,0.75)', lineHeight: 1.8, whiteSpace: 'pre-wrap', margin: 0, userSelect: 'text' }}>{studyMaterial[activeMilestone.id]}</p>
                  </div>

                  {tips[activeMilestone.id] && (
                    <div style={{ background: `linear-gradient(135deg, ${accent}12, ${accent}08)`, borderRadius: '14px', padding: '18px 20px', border: `1px solid ${accent}25` }}>
                      <p style={{ fontSize: '12px', color: accent, fontWeight: 700, margin: '0 0 12px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>💡 Pro Tips</p>
                      {tips[activeMilestone.id].map((tip, i) => (
                        <div key={i} style={{ display: 'flex', gap: '10px', marginBottom: '10px', alignItems: 'flex-start' }}>
                          <span style={{ fontSize: '12px', fontWeight: 700, color: accent, background: accent + '20', width: '20px', height: '20px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>{i + 1}</span>
                          <p style={{ margin: 0, fontSize: '13px', color: 'rgba(255,255,255,0.7)', lineHeight: 1.5 }}>{tip}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Action Buttons */}
              <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                <button onClick={() => generateStudyMaterial(activeMilestone)} disabled={loadingMaterial === activeMilestone.id}
                  style={{ padding: '10px 18px', borderRadius: '10px', border: `1px solid ${accent}44`, background: accent + '15', color: accent, cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
                  {loadingMaterial === activeMilestone.id ? '⏳ Generating...' : '✨ Study Material'}
                </button>
                <button onClick={() => navigate(`/flashcards/${topicId}/${activeMilestone.id}`)}
                  style={{ padding: '10px 18px', borderRadius: '10px', border: '1px solid rgba(251,146,60,0.3)', background: 'rgba(251,146,60,0.1)', color: '#fdba74', cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
                  🃏 Flashcards
                </button>
                <button onClick={() => navigate(`/chat/${topicId}/${activeMilestone.id}`)}
                  style={{ padding: '10px 18px', borderRadius: '10px', border: '1px solid rgba(251,146,60,0.3)', background: 'rgba(251,146,60,0.1)', color: '#fdba74', cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
                  🎓 Chat Tutor
                </button>
                {!activeMilestone.completed && (
                  <button onClick={() => navigate(`/quiz/${topicId}/${activeMilestone.id}?autoComplete=true`)}
                    style={{ padding: '10px 18px', borderRadius: '10px', border: 'none', background: 'linear-gradient(135deg, #16a34a, #15803d)', color: 'white', cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
                    ✓ Mark Complete
                  </button>
                )}
                <button onClick={() => navigate(`/quiz/${topicId}/${activeMilestone.id}`)}
                  style={{ padding: '10px 18px', borderRadius: '10px', border: '1px solid rgba(234,179,8,0.3)', background: 'rgba(234,179,8,0.08)', color: '#fbbf24', cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
                  📝 Quiz
                </button>
                {selected < milestones.length - 1 && (
                  <button onClick={() => setSelected(selected + 1)}
                    style={{ padding: '10px 18px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.6)', cursor: 'pointer', fontSize: '13px' }}>
                    Next →
                  </button>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}